Ext.define('app.extJsBook',{
								config:{
										title:'',
										price:'',
										author:''
										},
								constructor:function(config){
									this.initConfig(config)
								}
							});